#! /usr/bin/perl

chomp($version = `./version -c`);
$dist_name = "multigraph-$version-examples";

sub sys {
    my $cmd = shift;
    print("$cmd\n");
    return system($cmd);
}

sys("/bin/rm -f $dist_name.zip");
sys("/bin/rm -rf $dist_name");
sys("mkdir $dist_name");
sys("cp LICENSE.txt $dist_name");
sys("mkdir $dist_name/Multigraph");

open(IN, "<html/Multigraph.js");
open(OUT, ">$dist_name/Multigraph.js");
while (<IN>) {
    #s|^var\s+multigraphSwfRelPath\s*=\s*.*$|var multigraphSwfRelPath = "";|;
    s|^var\s+multigraphSwf\s*=\s*.*$|var multigraphSwf = "Multigraph.swf";|;
    s|return scriptLocation|return scriptLocation+'Multigraph/'|;
    print OUT;
}
close(IN);
close(OUT);
sys("cp Multigraph.swf $dist_name/Multigraph");
sys("cp html/swfobject.js $dist_name/Multigraph");
sys("cp html/expressInstall.swf $dist_name/Multigraph");
sys("./make-examples");
sys("(cd html ; tar cf - examples) | (cd $dist_name ; tar xvf -)");
sys("zip -r $dist_name.zip $dist_name");
sys("/bin/rm -rf $dist_name");
