#! /usr/bin/perl

open(SVN, "svn info .|");
$url = "";
while (<SVN>) {
    chomp;
    if ( ($u) = /^URL: (\S+)$/ ) {
	$url = $u;
	last;
    }
}
close(SVN);

open(SVN, "svn info $url|");
$revision = "0";
while (<SVN>) {
    chomp;
    if ( ($r) = /^Revision: (\d+)$/ ) {
	$revision = $r;
	last;
    }
}
close(SVN);

open(OUT, ">SEQUENCE");
printf(OUT "%s", $revision);
close(OUT);

