#! /usr/bin/perl

##
## This script checks to make sure that the list of classes in "compc-config.xml" is
## up to date.  It does this by running the script "swcclasses", which generates the
## current list of classes, and comparing to the current "compc-config.xml".  If there
## are any differences, this script replaces "compc-config.xml" with the new version.
## If there aren't any differences, "compc-config.xml" is left unchanged.
##

$configfile = shift;  # compc-config.xml

if ($configfile eq "compc-config.xml") {
    $target = "SWC";
} elsif ($configfile eq "mxmlc-config.xml") {
    $target = "SWF";
} else {
    die "usage: update-config { compc-config.xml | mxmlc-config.xml }\n";
}

###
### Create new version of $configfile in the /tmp directory:
###
open(IN, "<$configfile");
open(OUT, ">/tmp/$configfile");
while (<IN>) {
    if (!/<class>/) {
	print OUT $_;
    }
    if (/<include-classes>/) {
	open(SRCCLASSES, "./srcclasses $target |");
	while (chomp($class = <SRCCLASSES>)) {
	    printf(OUT "      <class>%s</class>\n", $class);
	}
	close(SRCCLASSES);
    }
}
close(OUT);
close(IN);

###
### Compare current version to new version, and if different, replace:
###
$code = system("cmp /tmp/$configfile ./$configfile > /dev/null");
if ($code) {
    system("cp /tmp/$configfile ./$configfile");
    printf("$configfile updated\n");
} else {
    printf("$configfile unchanged\n");
}

###
### Remove new version from /tmp:
###
unlink("/tmp/$configfile");
