#! /usr/bin/perl

@vals = ();
while (<>) {
    chomp;
    ($year,$val) = split(/,/);
    push(@vals, $val);
    if (@vals==12) {
        printf("%4d,%.4f\n", substr($year,0,4), avg(@vals));
        @vals = ();
    }
}

sub avg {
    my @vals = @_;
    my $n = (@vals+0);
    my $sum = 0.0;
    while (@vals) {
        $sum += shift(@vals);
    }
    return $sum/$n;
}

