#! /usr/bin/perl

$lines = [];
open(IN, "<paleo1000.csv");
while (<IN>) {
    chomp;
    @fields = split(/,/);
    if (@fields==2) {
        push(@$lines, [$fields[0], $fields[1]]);
    }
}
close(IN);

$nlines = @{$lines};
for ($i=0; $i<$nlines; ++$i) {
#    $x = 1000 * $lines->[$nlines-1-$i]->[0];
#    $y = $lines->[$nlines-1-$i]->[1];
    $x = $lines->[$i]->[0] / 1000.0;
    $y = $lines->[$i]->[1];
    printf("%s,%s\n", $x, $y);
}

